### ISSUE TITLE
Utility functions (clan, sein) don't support numbers as arguments

### ISSUE THREAD

**Issue by Fang-** [urbit/ob-js#18]
```
TypeError: name.replace is not a function
    at patp2syls (/urbit-ob/src/internal/co.js:56:8)
    at isValidPat (/urbit-ob/src/internal/co.js:366:16)
    at patp2hex (/urbit-ob/src/internal/co.js:144:7)
    at patp2bn (/urbit-ob/src/internal/co.js:181:10)
    at clan (/urbit-ob/src/internal/co.js:318:16)
    at Object.sein (/urbit-ob/src/internal/co.js:338:15)
```

I might just dive in and patch this up myself tomorrow, but @jtobin might not want me kicking up dirt all over his codebase. (;

**Comment by jtobin** [comment]
PRs always welcome!  They might just not be accepted, is all.. 😈 

I actually prefer the current behaviour of restricting the inputs to strings (i.e. `@p` values) only, and making the user call e.g. `patp2dec` if they need to get a corresponding point number.  Branching on types always makes me feel icky -- what is this, Idris?! 😄 

(Granted, some of the internals, e.g. `bn.js`, will handle both string & number inputs just fine.  But I didn't write the branching conditions myself, so I could outsource the distaste.)

Given this is a library, rather than an application, I'd be inclined to require users to cast between their input types explicitly.  *Especially* users named @Fang-.  But I'm not terribly picky about this one.

**Comment by Fang-** [comment]
> I actually prefer the current behaviour of restricting the inputs to strings (i.e. `@p` values) only, and making the user call e.g. `patp2dec` if they need to get a corresponding point number.

Two things:
1. Won't this lead to back-and-forth conversions? Most all of the logic uses numbers internally, so converting my number to a `@p` prior to calling feels wasteful.
2. There is no `dec2patp`!

**Comment by jtobin** [comment]
1. Perhaps some, but I haven't actually found it to be burdensome.  You can always get away with e.g. `sein(patp(123))`.  And there's only a single use of `sein` in Bridge, and zero of `clan`, so it doesn't pop up a lot.

2. That one is just plain old `patp`, because it's the most common case.  For `patp2dec` I had to think of a name that gelled with `patp2hex`, etc. 😄

**Comment by Fang-** [comment]
> And there's only a single use ... in Bridge

This is `urbit-ob`, not `urbit-ob-for-bridge`!

But alright, alright, fair enough. I'll pack up my premature optimization and leave. [For now.](https://66.media.tumblr.com/e62da66d9d029ac71f412f9f35c324f4/tumblr_mzp4uw8vKO1qcga5ro1_500.gif)
